# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_signec.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
#frame_Camara

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1155, 628)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(660, 10, 16, 571))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.init_button = QtWidgets.QPushButton(self.centralwidget)
        self.init_button.setGeometry(QtCore.QRect(770, 350, 91, 91))
        self.init_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/play-button-4210.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.init_button.setIcon(icon)
        self.init_button.setIconSize(QtCore.QSize(75, 75))
        self.init_button.setFlat(True)
        self.init_button.setObjectName("init_button")
        self.restart_button = QtWidgets.QPushButton(self.centralwidget)
        self.restart_button.setGeometry(QtCore.QRect(950, 350, 101, 91))
        self.restart_button.setStyleSheet("font-family: impact; \n"
"font-size: 20px;")
        self.restart_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/reboot-restart-green-circle-round-arrow-24688.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.restart_button.setIcon(icon1)
        self.restart_button.setIconSize(QtCore.QSize(75, 75))
        self.restart_button.setFlat(True)
        self.restart_button.setObjectName("restart_button")
        self.guide_button = QtWidgets.QPushButton(self.centralwidget)
        self.guide_button.setGeometry(QtCore.QRect(770, 480, 91, 81))
        self.guide_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/books-4993.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.guide_button.setIcon(icon2)
        self.guide_button.setIconSize(QtCore.QSize(75, 75))
        self.guide_button.setFlat(True)
        self.guide_button.setObjectName("guide_button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 30, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Haettenschweiler")
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.frame_Camara = QtWidgets.QLabel(self.centralwidget)
        self.frame_Camara.setGeometry(QtCore.QRect(20, 80, 640, 480))
        self.frame_Camara.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Camara.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Camara.setObjectName("frame_Camara")
        self.LOGO = QtWidgets.QPushButton(self.centralwidget)
        self.LOGO.setGeometry(QtCore.QRect(700, 10, 411, 211))
        self.LOGO.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("SignECLogo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.LOGO.setIcon(icon3)
        self.LOGO.setIconSize(QtCore.QSize(1300, 600))
        self.LOGO.setFlat(True)
        self.LOGO.setObjectName("LOGO")
        self.LABEL_gUIA = QtWidgets.QLabel(self.centralwidget)
        self.LABEL_gUIA.setGeometry(QtCore.QRect(750, 440, 131, 41))
        self.LABEL_gUIA.setStyleSheet("font-family: impact;\n"
"font-size: 20px;")
        self.LABEL_gUIA.setTextFormat(QtCore.Qt.AutoText)
        self.LABEL_gUIA.setAlignment(QtCore.Qt.AlignCenter)
        self.LABEL_gUIA.setObjectName("LABEL_gUIA")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(780, 325, 71, 21))
        self.label_2.setStyleSheet("font-family: impact;\n"
"font-size: 20px;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(960, 320, 81, 31))
        self.label_3.setStyleSheet("font-family: impact;\n"
"font-size: 20px;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_textsigns = QtWidgets.QLabel(self.centralwidget)
        self.label_textsigns.setGeometry(QtCore.QRect(750, 240, 331, 61))
        self.label_textsigns.setStyleSheet("padding: 15px;\n"
"font-family: Courier;\n"
"font-size: 30px;\n"
"border: 2px dotted black;\n"
"")
        self.label_textsigns.setObjectName("label_textsigns")
        self.test_button = QtWidgets.QPushButton(self.centralwidget)
        self.test_button.setGeometry(QtCore.QRect(950, 480, 91, 81))
        self.test_button.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/icon-challengue.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.test_button.setIcon(icon4)
        self.test_button.setIconSize(QtCore.QSize(75, 75))
        self.test_button.setFlat(True)
        self.test_button.setObjectName("test_button")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(950, 450, 91, 21))
        self.label_4.setStyleSheet("font-size: 20px;\n"
"font-family: impact;\n"
"")
        self.label_4.setMidLineWidth(-5)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1155, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Cámara"))
        self.LABEL_gUIA.setText(_translate("MainWindow", "GUÍA DE SEÑAS"))
        self.label_2.setText(_translate("MainWindow", "INICIAR"))
        self.label_3.setText(_translate("MainWindow", "REINICIAR"))
        self.label_textsigns.setText(_translate("MainWindow", "TextLabel"))
        self.label_4.setText(_translate("MainWindow", "DESAFÍO"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
